package com.pfe.challenge.Model;

public enum PackType {

    SERENITE,
    SUPER_SECURITE,
    SECURITE_PLUS,
    SECURITE,
    ETUDIANT,
    PROPRIETAIRE_NON_OCCUPANT,
    VISA,
    GOLD,
    ASSISTANCE_BUSINESS,
    ASSISTANCE_ETUDIANT,
    ASSISTANCE_PELERINAGE,
}
